

import './globals.css'

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Hello</h1>
        
        {children} 

        <footer>Harsh</footer> 
      </body>
    </html>
  )
}